name: Metrics
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: V1perzin
          filename: github-metrics.svg   # <- garante o nome que seu README usa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Recife
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 14
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_trim: yes
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_sort: stars
