name: Metrics
on:
  schedule:
    - cron: "0 3 * * *"   # roda todo dia ~00h no Brasil
  workflow_dispatch:        # permite rodar manualmente
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: V1perzin
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Recife

          # ----- Linguagens -----
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 14

          # ----- Calendário anual de contribuições -----
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # ----- Conquistas (achievements) -----
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes

          # ----- Hábitos de commit -----
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_trim: yes

          # ----- Tópicos (tags de interesses do repo) -----
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_sort: stars

          # (Opcional) AniList - anime vibes 😎
          # plugin_anilist: yes
          # plugin_anilist_user: SEU_USUARIO_ANILIST
          # plugin_anilist_sections: watching, favorites
