name: Metrics
on:
  schedule:
    - cron: "0 3 * * *"   # atualiza todo dia ~00h no Brasil (ajuste se quiser)
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: V1perzin
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Recife
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
