name: Generate Snake
on:
  schedule:
    - cron: "30 2 * * *"   # ~23:30 no Brasil (UTC 02:30)
  workflow_dispatch:

permissions:
  contents: write   # necessário para gravar na branch 'output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: V1perzin
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
